- copy:
    src: ../files/vscode.repo
    dest: /etc/yum.repos.d/vscode.repo
  become: true
- dnf:
    update_cache: true
    name:
      - "vim-enhanced"
      - emacs
      - code
    state: latest
  become: true