- hosts: 127.0.0.1
  connection: local
  become: true
  vars_files:
    - ./vars.yml
  roles:
    - pre_requisites # rmp free / non free repos, pip, updates ...
    - dev_packages
    - dev_libraries # requires dev_packages
    - dev_languages
    - gui
    - git # requires npm from dev_languages for gitmoji
    - editors # vscode, vim, emacs
    - docker
    - zsh
    - teams
    - ssh
    - virtualbox
    - telegram
    - zoom
    - tools
    - obsidian
    - folders
    - discord
    - role: diodonfrost.terraform
    - media
    - tor
    - kubernetes
    - keyboard
