- hosts: 127.0.0.1
  connection: local
  become: true
  vars_files:
    - ./vars.yml
  roles:
    - pre_requisites # rmp free / non free repos, pip, updates ...
    - dev_packages
    - game_dev_libraries # requires dev_packages
    - gui
    - git
    - editors # vscode, vim, emacs
    - docker
    - zsh
    - teams
    - ssh
    - virtualbox
    - zoom
    - tools
    - obsidian
    - folders
    - discord
    - terraform