- name: install development libraries
  dnf:
    name:
      - alsa-lib-devel
      - mesa-libGL-devel
      - libX11-devel
      - libXrandr-devel
      - libXi-devel
      - libXcursor-devel
      - libXinerama-devel
      - wayland-devel
      - libxkbcommon-devel
      - wayland-protocols-devel
- name: "install build tools: cmake"
  dnf:
    name:
      - gcc-c++
      - cmake