- name: add gpg key
  rpm_key:
    state: present
    key: https://zoom.us/linux/download/pubkey
  become: true
- name: install zoom
  dnf:
    name: https://zoom.us/client/latest/zoom_x86_64.rpm
  become: true