- name: install dependencies
  dnf:
    name:
      - "@development-tools"
      - kernel-headers
      - kernel-devel
      - dkms
      - elfutils-libelf-devel
      - qt5-qtx11extras
  become: true
# - name: add repo
#   copy:
#     src: ../files/virtualbox.repo
#     dest: /etc/yum.repos.d/virtuabox.repo
#   become: true
# - name: add gpg key
#   rpm_key:
#     state: present
#     key: https://www.virtualbox.org/download/oracle_vbox.asc
#   become: true
# - name: install virtualbox
#   dnf:
#     name: VirtualBox-6.1
#   become: true
# - name: add user to virtualbox group
#   user:
#     groups: vboxusers
#     append: true
#   become: true