- name: install dependencies
  dnf:
    name:
      - "@development-tools"
      - kernel-headers
      - kernel-devel
      - dkms
      - elfutils-libelf-devel
      - qt5-qtx11extras
- name: install virtualbox
  dnf:
    update_cache: true
    name: VirtualBox
- name: add user to virtualbox group
  user:
    name: "{{ user }}"
    groups: vboxusers
    append: true
- name: install other dependencies
  dnf:
    name:
      - akmod-VirtualBox
      - kernel-devel-5.17.5-300.fc36.x86_64
- name: update akmods
  shell: akmods --kernels 5.17.5-300.fc36.x86_64
- name: restart systemd
  ansible.builtin.systemd:
    daemon_reload: true
- name: start vboxdrv
  ansible.builtin.systemd:
    state: started
    name: vboxdrv
