- name: add rpm repository
  dnf:
    name: 'https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version }}.noarch.rpm'
    state: present
    disable_gpg_check: true
  become: true
- name: install discord
  dnf:
    update_cache: true
    name: discord
    state: present
  become: true