- dnf:
    name:
      - docker
      - docker-compose
    state: present
  become: true
- name: Ensure group "docker" exists with correct gid
  group:
    name: docker
    state: present
  become: true
- name: Add the user to the docker group
  user:
    name: "{{ user }}"
    groups: docker
    append: true
  become: true
- name: Check if file exists
  ansible.builtin.stat:
    path: /usr/bin/lazydocker
  register: check_file_name
- command: sh -c "$(curl -fsSL https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_update_linux.sh)"
  become: true
  args:
    creates: /usr/bin/lazydocker